project:
  type: website

website:
  title: "Study Guide for UDPs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - overview.qmd
      - understanding-udp.qmd
      - ai-driven-dev.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



