project:
  type: book

book:
  title: "Study Guide for UDPs"
  author:
    - "Andrey Malyukov"
    - "Bogdan Zachepa"
    - "Vladimir Keller"
  date: "4/16/2025"
  chapters:
    - index.qmd
    - overview.qmd
    - understanding-udp.qmd
    - ai-driven-dev.qmd
    - ethics-security-governance.qmd
    - methodologies.qmd
    - skills.qmd
    - sdlc.qmd
  appendices:
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



