project:
  type: book

book:
  title: "Study Guide for UDPs"
  author:
    - "Andrey Malyukov"
    - "Bogdan Zachepa"
    - "Vladimir Keller"
  date: "4/16/2025"
  chapters:
    - index.qmd
    - understanding-udp.qmd
    - ai-driven-dev.qmd
    - ethics-security-governance.qmd
    - methodologies.qmd
    - skills.qmd
    - sdlc.qmd
  appendices:
    - summary.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

number-depth: 0

format:
  html:
    theme:
      - cosmo
      - brand
    css: webex.css
    include-after-body: webex.js
  pdf:
    documentclass: scrreprt



