project:
  type: book

book:
  title: "Study Guide for UDPs"
  author:
    - "Andrey Malyukov"
    - "Bogdan Zachepa"
    - "Vladimir Keller"
    - "Roza Bass"
  date: "4/23/2025"
  chapters:
    - index.qmd
    - understanding-udp.qmd
    - ai-driven-dev.qmd
    - ethics-security-governance.qmd
    - methodologies.qmd
    - skills.qmd
    - sdlc.qmd
    - summary.qmd
    - references.qmd
  page-navigation: true
  repo-url: https://github.com/ds-an/udp-study-guide

bibliography: references.bib

number-depth: 0

format:
  html:
    theme:
      - zephyr
    css: webex.css
    include-after-body: webex.js
  # pdf:
  #   documentclass: scrreprt



